on:
  workflow_run:
    workflows: ["Main release"]
    types: [completed]

permissions:
    contents: write
    packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install dependencies
        run: |
          go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v -race -buildvcs ./...
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64